---
title: 3A Informatica compiti
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: pival801@gmail.com
description: 3A Informatica compiti
baseurl: ''
url: https://3aiet.github.io
github_username: 3AIET
markdown: kramdown
plugins:
- jekyll-feed
